"""
PYDANTIC SCHEMAS — API Request/Response Models
===============================================
These define the EXACT shape of data flowing in and out of your API.

PYDANTIC vs SQLALCHEMY MODELS — WHAT'S THE DIFFERENCE?
  - SQLAlchemy models → define database tables (how data is STORED)
  - Pydantic models  → define API contracts (how data is SENT/RECEIVED)

  They often look similar but serve different purposes:
  - SQLAlchemy: "This column is an Integer in the database"
  - Pydantic:   "This field must be an int in the JSON request/response"

WHY SEPARATE THEM?
  You might store 20 fields in the database but only send 10 to the frontend.
  You might accept 5 fields in a request but store 15 (adding timestamps, IDs, etc.)
  Separation keeps your API clean and your database flexible.

KEY PYDANTIC FEATURES:
  - Automatic validation: wrong types get rejected with clear error messages
  - Serialization: converts Python objects to JSON (and back) automatically
  - Documentation: FastAPI uses these to generate Swagger API docs
  - Optional fields: use Optional[type] for fields that might be null
"""

from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime


class ColumnStats(BaseModel):
    """
    Statistics for a single column in the uploaded CSV.
    
    This is the core unit of analysis — every column gets one of these.
    Numeric columns get full stats; categorical columns get counts only.
    """
    name: str = Field(..., description="Column name from the CSV header")
    dtype: str = Field(..., description="Data type: numeric, categorical, datetime, boolean")
    
    # Data quality metrics
    total_count: int = Field(..., description="Total number of rows")
    missing_count: int = Field(..., description="Number of missing/null values")
    missing_pct: float = Field(..., description="Percentage of missing values (0-100)")
    unique_count: int = Field(..., description="Number of distinct values")
    
    # Numeric-only statistics (None for categorical columns)
    # Optional[float] means "this can be a float OR None"
    mean: Optional[float] = Field(None, description="Arithmetic mean (numeric only)")
    median: Optional[float] = Field(None, description="Median / 50th percentile (numeric only)")
    std: Optional[float] = Field(None, description="Standard deviation (numeric only)")
    min_val: Optional[float] = Field(None, description="Minimum value (numeric only)")
    max_val: Optional[float] = Field(None, description="Maximum value (numeric only)")
    skewness: Optional[float] = Field(None, description="Distribution skewness (numeric only)")
    
    # Categorical-only
    top_values: Optional[List[dict]] = Field(None, description="Top 5 most frequent values with counts")


class Insight(BaseModel):
    """
    A single insight generated by the rule engine.
    
    Each insight is a ranked, categorized finding about the data.
    The frontend sorts these by severity and displays them as cards.
    
    SEVERITY LEVELS:
      - critical: Serious data quality issue that WILL affect analysis
      - warning:  Notable finding that MIGHT affect analysis  
      - info:     Interesting observation, no action needed
    
    SCORE:
      A float from 0.0 to 1.0 used for ranking within the same severity.
      Higher score = more important. This lets us show the most impactful
      insights first even within the same severity level.
    """
    severity: str = Field(..., description="critical, warning, or info")
    category: str = Field(..., description="Category: missing_data, correlation, skewness, etc.")
    message: str = Field(..., description="Human-readable insight text")
    column: Optional[str] = Field(None, description="Which column this insight is about (if any)")
    details: Optional[str] = Field(None, description="Additional context or recommendation")
    score: float = Field(..., description="Ranking score within severity level (0.0 to 1.0)")


class CorrelationPair(BaseModel):
    """A pair of correlated columns with their correlation coefficient."""
    column_a: str
    column_b: str
    correlation: float  # Pearson correlation coefficient (-1 to 1)
    strength: str       # "strong", "moderate", "weak"


class AnalysisResponse(BaseModel):
    """
    The complete response from POST /analyze.
    
    This is the main payload that drives the entire frontend.
    Every panel (stats, insights, charts) reads from this single response.
    """
    # File metadata
    filename: str
    file_size_bytes: int
    
    # Dataset overview
    row_count: int
    column_count: int
    memory_usage_mb: float
    
    # Detailed column statistics
    columns: List[ColumnStats]
    
    # Numeric column names (for frontend chart selection)
    numeric_columns: List[str]
    categorical_columns: List[str]
    datetime_columns: List[str]
    
    # Ranked insights from the rule engine
    insights: List[Insight]
    insight_summary: dict = Field(
        default_factory=dict,
        description="Count by severity: {critical: N, warning: N, info: N}"
    )
    
    # Correlation data
    correlation_matrix: Optional[dict] = Field(
        None, description="Correlation matrix as nested dict for heatmap"
    )
    notable_correlations: List[CorrelationPair] = Field(
        default_factory=list,
        description="Correlations with |r| > 0.5, sorted by absolute value"
    )
    
    # Charts — base64 encoded PNG images
    charts: dict = Field(
        default_factory=dict,
        description="Chart name → base64 PNG string"
    )
    
    # Distribution data for frontend Recharts (interactive charts)
    distributions: Optional[dict] = Field(
        None, description="Histogram data for numeric columns (for Recharts)"
    )
    
    # Plain English summary
    summary: str = Field(..., description="Auto-generated plain-English overview of the dataset")


class UploadHistoryItem(BaseModel):
    """A single item in the upload history list."""
    id: int
    filename: str
    row_count: int
    column_count: int
    insights_count: int
    critical_count: int
    warning_count: int
    uploaded_at: datetime

    class Config:
        from_attributes = True  # Allows creating from SQLAlchemy models


class ErrorResponse(BaseModel):
    """Standardized error response format."""
    error: str
    detail: str
    suggestion: Optional[str] = None
