/**
 * INSIGHTS PANEL — Ranked Data Quality Insights
 * ==============================================
 * Displays the insights generated by the 20-rule engine,
 * sorted by severity (Critical → Warning → Info).
 * 
 * DESIGN PATTERN: Card-based UI with expandable details.
 * Each insight is a card with severity badge, message, and
 * optional expandable detail section.
 * 
 * This component demonstrates:
 *   - Array filtering and mapping
 *   - Conditional CSS classes
 *   - useState for expand/collapse
 *   - Clean data presentation
 */
"use client";

import { useState } from "react";
import {
  AlertOctagon,
  AlertTriangle,
  Info,
  ChevronDown,
  ChevronUp,
  Shield,
  TrendingUp,
} from "lucide-react";

export default function InsightsPanel({ data }) {
  const [expandedIdx, setExpandedIdx] = useState(null);
  const [filter, setFilter] = useState("all"); // all, critical, warning, info

  if (!data || !data.insights) return null;

  const { insights, insight_summary, summary } = data;

  // Filter insights based on selected severity
  const filteredInsights =
    filter === "all"
      ? insights
      : insights.filter((i) => i.severity === filter);

  return (
    <div className="space-y-5 animate-slide-up">
      {/* ─── Summary Card ─── */}
      {summary && (
        <div className="glass-card p-5 border-l-4 border-l-emerald-500">
          <div className="flex items-start gap-3">
            <TrendingUp className="w-5 h-5 text-emerald-400 mt-0.5 flex-shrink-0" />
            <div>
              <h3 className="text-sm font-semibold text-[var(--text-primary)] mb-1">
                Dataset Summary
              </h3>
              <p className="text-sm text-[var(--text-secondary)] leading-relaxed">
                {summary}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* ─── Severity Filter Tabs ─── */}
      <div className="flex items-center gap-2 flex-wrap">
        <FilterTab
          label="All"
          count={insights.length}
          active={filter === "all"}
          onClick={() => setFilter("all")}
          color="gray"
        />
        <FilterTab
          label="Critical"
          count={insight_summary?.critical || 0}
          active={filter === "critical"}
          onClick={() => setFilter("critical")}
          color="red"
        />
        <FilterTab
          label="Warning"
          count={insight_summary?.warning || 0}
          active={filter === "warning"}
          onClick={() => setFilter("warning")}
          color="amber"
        />
        <FilterTab
          label="Info"
          count={insight_summary?.info || 0}
          active={filter === "info"}
          onClick={() => setFilter("info")}
          color="blue"
        />
      </div>

      {/* ─── Insight Cards ─── */}
      <div className="space-y-2">
        {filteredInsights.length === 0 ? (
          <div className="text-center py-8 text-[var(--text-tertiary)]">
            <Shield className="w-10 h-10 mx-auto mb-2 opacity-40" />
            <p>No {filter !== "all" ? filter : ""} insights found</p>
          </div>
        ) : (
          filteredInsights.map((insight, idx) => (
            <InsightCard
              key={idx}
              insight={insight}
              isExpanded={expandedIdx === idx}
              onToggle={() =>
                setExpandedIdx(expandedIdx === idx ? null : idx)
              }
              animDelay={idx * 50}
            />
          ))
        )}
      </div>
    </div>
  );
}

/* ─── Filter Tab Sub-Component ─── */
function FilterTab({ label, count, active, onClick, color }) {
  const colorMap = {
    gray: active
      ? "bg-[var(--surface-tertiary)] text-[var(--text-primary)] border-[var(--text-tertiary)]"
      : "text-[var(--text-tertiary)] border-transparent hover:text-[var(--text-secondary)]",
    red: active
      ? "bg-red-500/10 text-red-400 border-red-500/30"
      : "text-[var(--text-tertiary)] border-transparent hover:text-red-400",
    amber: active
      ? "bg-amber-500/10 text-amber-400 border-amber-500/30"
      : "text-[var(--text-tertiary)] border-transparent hover:text-amber-400",
    blue: active
      ? "bg-blue-500/10 text-blue-400 border-blue-500/30"
      : "text-[var(--text-tertiary)] border-transparent hover:text-blue-400",
  };

  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border transition-all ${colorMap[color]}`}
    >
      {label}
      {count > 0 && (
        <span className="px-1.5 py-0.5 rounded-full text-[10px] bg-white/5">
          {count}
        </span>
      )}
    </button>
  );
}

/* ─── Insight Card Sub-Component ─── */
function InsightCard({ insight, isExpanded, onToggle, animDelay }) {
  const severityConfig = {
    critical: {
      icon: <AlertOctagon className="w-4 h-4" />,
      badge: "severity-critical",
      border: "border-l-red-500",
      iconColor: "text-red-400",
    },
    warning: {
      icon: <AlertTriangle className="w-4 h-4" />,
      badge: "severity-warning",
      border: "border-l-amber-500",
      iconColor: "text-amber-400",
    },
    info: {
      icon: <Info className="w-4 h-4" />,
      badge: "severity-info",
      border: "border-l-blue-500",
      iconColor: "text-blue-400",
    },
  };

  const config = severityConfig[insight.severity] || severityConfig.info;

  return (
    <div
      className={`glass-card overflow-hidden border-l-4 ${config.border} transition-all duration-200 hover:bg-[var(--surface-secondary)]`}
      style={{ animationDelay: `${animDelay}ms` }}
    >
      <div
        className="flex items-start gap-3 p-4 cursor-pointer"
        onClick={onToggle}
      >
        {/* Severity icon */}
        <div className={`mt-0.5 flex-shrink-0 ${config.iconColor}`}>
          {config.icon}
        </div>

        {/* Content */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1 flex-wrap">
            <span
              className={`px-2 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wider ${config.badge}`}
            >
              {insight.severity}
            </span>
            <span className="px-2 py-0.5 rounded text-[10px] font-medium bg-[var(--surface-tertiary)] text-[var(--text-tertiary)]">
              {insight.category.replace(/_/g, " ")}
            </span>
            {insight.column && (
              <span className="text-[10px] text-[var(--text-muted)] font-mono">
                → {insight.column}
              </span>
            )}
          </div>
          <p className="text-sm text-[var(--text-primary)] leading-relaxed">
            {insight.message}
          </p>
        </div>

        {/* Expand toggle */}
        {insight.details && (
          <div className="text-[var(--text-tertiary)] flex-shrink-0">
            {isExpanded ? (
              <ChevronUp className="w-4 h-4" />
            ) : (
              <ChevronDown className="w-4 h-4" />
            )}
          </div>
        )}
      </div>

      {/* Expanded details */}
      {isExpanded && insight.details && (
        <div className="px-4 pb-4 pt-0 ml-7">
          <div className="p-3 rounded-lg bg-[var(--surface-tertiary)]/50 border border-[var(--border-secondary)]">
            <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
              {insight.details}
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
